### ISSUE TITLE
CentOS 6.5 rpm install has no 'ivy' package

### ISSUE THREAD

**Issue by Sauraus** [jtimberman/ant-cookbook#5]
```text
Recipe: ant::install_package
  * package[ant] action install
    - install version 1.7.1-13.el6 of package ant
  * package[ant-contrib] action install
    - install version 1.0-0.10.b2.el6 of package ant-contrib
  * package[ivy] action install
    * No version specified, and no candidate version available for ivy
    ================================================================================
    Error executing action `install` on resource 'package[ivy]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    No version specified, and no candidate version available for ivy

uname -r
2.6.32-431.11.2.el6.x86_64
```

**Comment by austinkeeley** [comment]
I also received this error. Since I don't need Ivy, I changed the line in `recipes/install_package.rb` that specified the packages to install and removed `"ivy"`.

**Comment by iennae** [comment]
@Sauraus Thanks for filing this issue. Apologies for the delay in response. I'm updating the cookbook documentation to reflect that if using this cookbook that you want to use the install_source.rb recipe on those platforms. My plan is to do one last release of this cookbook in its current format to be compatible with Chef 11+, before rewriting as a resource driven cookbook that will be limited to Chef 12+.
