### ISSUE TITLE
URL ends up with extra forward slash

### ISSUE THREAD

**Issue by fletchowns** [jtimberman/ant-cookbook#9]
The URL attribute is defined with a forward slash: https://github.com/jtimberman/ant-cookbook/blob/master/attributes/default.rb#L21

And the recipe adds another forward slash: https://github.com/jtimberman/ant-cookbook/blob/master/recipes/install_source.rb#L29

So you end up with a url like this: http://archive.apache.org/dist/ant/binaries//apache-ant-1.9.7-bin.tar.gz

The apache.org server doesn't seem to care about the extra slash but when I mirrored the binary on Amazon S3 it does seem to care and it can't download it correctly. Workaround for me is easy of course, just remove the trailing slash from the url attribute.

Thanks for the handy cookbook!

**Comment by iennae** [comment]
Thanks for reporting this issue! I've gone ahead and pushed this fix to version 1.0.4 of this cookbook.
